### ISSUE TITLE
synQuery() does not seem to retrieve complex annotations

### ISSUE THREAD

**Issue by ArtemSokolov** [Sage-Bionetworks/synapser#195]
## Operating system

Ubuntu 18.04 LTS

## Description of the problem

Consider `syn16780473`, which is an example file containing a complex annotation `Field1`:

![screenshot from 2018-08-31 15-31-39](https://user-images.githubusercontent.com/1377144/44932335-01352e80-ad33-11e8-942c-6f4f58fd4bbf.png)

When calling `synQuery( 'select id,Field1 from entity where parentId=="syn12180284" and Field2==123' )`, the result seems to only contain "abc".

### Expected behavior

If the result of `synQuery()` above was stored into a variable named `r`, we expect that `r$results[[1]]$entity.Field1` would be `list( "abc", "def" )` to match `synGetAnnotations( "syn16780473" )$Field1`.

### Actual behavior

``` r
library( synapser )
#> 
#> TERMS OF USE NOTICE:
#>   When using Synapse, remember that the terms and conditions of use require that you:
#>   1) Attribute data contributors when discussing these data or results from these data.
#>   2) Not discriminate, identify, or recontact individuals or groups represented by the data.
#>   3) Use and contribute only data de-identified to HIPAA standards.
#>   4) Redistribute data only under these same terms of use.
synLogin()
#> Welcome, Artem Sokolov!
#> NULL

# synGetAnnotations() correctly retrieves both "abc" and "def"
str(synGetAnnotations( "syn16780473" ))
#> List of 2
#>  $ Field1:List of 2
#>   ..$ : chr "abc"
#>   ..$ : chr "def"
#>  $ Field2:List of 1
#>   ..$ : num 123

# synQuery() on the other hand retrieves only "abc"
str(synQuery( 'select id,Field1 from entity where parentId=="syn12180284" and Field2==123' ))
#> List of 2
#>  $ results             :List of 1
#>   ..$ :List of 2
#>   .. ..$ entity.id    : chr "syn16780473"
#>   .. ..$ entity.Field1:List of 1
#>   .. .. ..$ : chr "abc"
#>  $ totalNumberOfResults: num 1
```
Created on 2018-08-31 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

## Output of `sessionInfo()`

``` r
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] synapser_0.3.40

loaded via a namespace (and not attached):
[1] compiler_3.5.1        R6_2.2.2              tools_3.5.1          
[4] pack_0.1-1            PythonEmbedInR_0.2.24
```

**Comment by kimyen** [comment]
Hi @ArtemSokolov,
Thank you so much for a detailed Github issue. 

Unfortunately, `synQuery()` will be deprecated and removed in future releases dues to its performance. But no worries, we have built a different feature that helps query for entities filter by annotations more efficiently called File View.

Please see our documentation for how to use File View in synapser: https://r-docs.synapse.org/articles/fileview.html
You can also learn more about View at: https://docs.synapse.org/articles/views.html

Please let us know if you have question using File View, or if File View doesn't solve the problem mentioned above.
Thanks,
Kimyen

**Comment by ArtemSokolov** [comment]
Thanks, @kimyen. It seems that querying the File View doesn't retrieve complex annotations either:

``` r
## Create and synStore() the view
view <- EntityViewSchema( name = "Test View", parent = "syn12180284",
                         scopes = "syn12180284" )
view <- synStore(view)

## Query the view for syn16780473, whose parent is syn12180284
query <- paste("select id,name,Field1 from", view$properties$id,
               "where parentId = 'syn12180284'")
results <- synTableQuery( query )
as.data.frame(results)
#     ROW_ID ROW_VERSION                             ROW_ETAG          id
# 1 16780473           1 15d40a3a-7153-4954-a3d5-6debaef56cc8 syn16780473
#         name Field1
# 1 mtcars.csv    abc

## Double-check that Field1 of syn16780473 is still a complex annotation
synGetAnnotations( "syn16780473" )$Field1
# [[1]]
# [1] "abc"
#
# [[2]]
# [1] "def"
```

It's possible that the query correctly retrieves both `"abc"` and `"def"`, but the latter gets lost when coercing the `synapseclient.table.CsvFileTable` object to a data frame. Is there another way to traverse the results object?

I think the base `data.frame` type in R is not well-suited for storing complex annotations in general. One possible extension is to make use of [`tibble` from tidyverse](https://tibble.tidyverse.org/) to capture complex annotation structures. For example, the expected output for the query above would be:

``` r
## Expected output for synTableQuery( query ) with query =
##   "select id,name,Field1 from syn16787213 where parentId = 'syn12180284'"
expout <- tibble::data_frame( id = "syn16780473", name = "mtcars.csv",
                              Field1 = list(list( "abc", "def" )) )
# # A tibble: 1 x 3
#   id          name       Field1    
#   <chr>       <chr>      <list>    
# 1 syn16780473 mtcars.csv <list [2]>

identical( expout$Field1[[1]], synGetAnnotations( "syn16780473" )$Field1 )
# [1] TRUE
```

**Comment by kimyen** [comment]
@ArtemSokolov , 

> It's possible that the query correctly retrieves both "abc" and "def", but the latter gets lost when coercing the synapseclient.table.CsvFileTable object to a data frame. Is there another way to traverse the results object?

The query downloaded the result data into a csv. `as.data.frame` reads the csv into an R `data.frame`. You can inspect the resulting data in `results$filepath`
Notes: a View is a Table. If you want to explore what one can do with a Table, please see: https://r-docs.synapse.org/articles/tables.html

> I think the base data.frame type in R is not well-suited for storing complex annotations in general. One possible extension is to make use of tibble from tidyverse to capture complex annotation structures. 

Please feel free to read in the resulting data from the csv into any R data type that you like. I will look into if the View itself contains the whole list of annotations in the first place.

**Comment by kimyen** [comment]
@ArtemSokolov 
I verified that the problem is View does not handle annotations with multiple items, and opened a Jira ticket: https://sagebionetworks.jira.com/browse/PLFM-5111. Development process will be tracked in the Jira ticket.

**Comment by ArtemSokolov** [comment]
Thank you, @kimyen, for the pointers on working with the query results and for opening a Jira ticket.

**Comment by brucehoff** [comment]
If the problem persists, please contact https://www.synapse.org/#!SynapseForum:default or synapseInfo@sagebase.org.
