### ISSUE TITLE
can't login in

### ISSUE THREAD

**Issue by David931229** [Sage-Bionetworks/synapser#204]
> library(synapser)
> synLogin()
Error in value[[3L]](cond) : No credentials provided.

I have registered a Synapse account. But when I run the code, I got this error. How can I get the place to login in  to my account.

**Comment by kimyen** [comment]
Hi @David931229 ,

Please specify your username and password as parameters for `synLogin()` as described in the `synapser` client docs: https://r-docs.synapse.org/articles/synapser.html#connecting-to-synapse

For questions about using the client, please post them in our discussion forum: https://www.synapse.org/#!SynapseForum:default

**Comment by David931229** [comment]
@kimyen Thank you. This helps me a lot.
