### ISSUE TITLE
Unmet dependency on Debian 9: libffi-dev

### ISSUE THREAD

**Issue by attilagk** [Sage-Bionetworks/synapser#233]
## Operating system

```
myprompt$ uname -a
Linux attila-ThinkS 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```
## Description of the problem

On Debian 9 (Stretch) the upgrade to synapser 0.5.45 failed with the error below.  Installing libffi-dev solved the problem.

```
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
ERROR: configuration failed for package ‘synapser’
* removing ‘/usr/local/lib/R/site-library/synapser’
* restoring previous ‘/usr/local/lib/R/site-library/synapser’
```

## Output of `sessionInfo()`

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.20     setwidth_1.0-4 colorout_1.0-2

loaded via a namespace (and not attached):
[1] compiler_3.4.1 tools_3.4.1   
```

**Comment by kimyen** [comment]
Hi @attilagk ,

We documented the system dependencies that `synapser` required here: https://r-docs.synapse.org/articles/systemDependencies.html

However, we still need to catch the installation error early and print something more useful for the users.

**Comment by attilagk** [comment]
Hi @kimyen thanks for the info.  Sorry I didn't notice the page on synapser's dependencies.  For novice users I would include a hyperlink in the [Installation](https://r-docs.synapse.org/index.html#installation) section of the home page to the [Dependencies](https://r-docs.synapse.org/articles/systemDependencies.html) page.

**Comment by kimyen** [comment]
Thank you for the thoughtful suggestion! I created a Jira ticket to track the progress: https://sagebionetworks.jira.com/browse/SYNR-1393. It should be done by the next release.
