### ISSUE TITLE
broken link to software dependencies

### ISSUE THREAD

**Issue by bswhite** [Sage-Bionetworks/synapser#258]
The following link to software dependencies under install:

https://github.com/Sage-Bionetworks/synapser/blob/master/articles/systemDependencies.html

is broken.

**Comment by kimyen** [comment]
@bswhite , thank you for reporting this. Before the fix is released, please use: https://r-docs.synapse.org/articles/systemDependencies.html

**Comment by kimyen** [comment]
The link is fixed.
