### ISSUE TITLE
ENH: get API Key

### ISSUE THREAD

**Issue by muschellij2** [Sage-Bionetworks/synapser#277]
## Operating system

Max OSX

## Description of the problem

Default in `synLogin` is that no credentials are given.  Should add a check that 
```r
if (is.null(email) && is.null(password)) {
   if (is.null(apiKey)) {
       apiKey = Sys.getenv("SYNAPSE_API_KEY")
   }
}
```
so that if you have a `SYNAPSE_API_KEY` variable set in `~/.Renviron` or environment (and using R from the terminal), then it will auto login.

### Expected behavior

Login if API set in ~/.Renviron

### Actual behavior

Fails if no credentials given

**Comment by brucehoff** [comment]
Sorry for the late reply.  You can store your API key in a .synapseConfig file, as explained in https://r-docs.synapse.org/articles/manageSynapseCredentials.html

**Comment by muschellij2** [comment]
I agree, but why not add the functionality for it to check in `~/.Renviron` after checking for the config file?  I feel as most users add to `~/.Renviron`.  Otherwise, if that's not the case, what about a function that's like `generate_synapse_config(email, username, api_key)`?
