### ISSUE TITLE
arm64 binary for M1 Mac not available

### ISSUE THREAD

**Issue by bunnell** [Sage-Bionetworks/synapser#302]
## Operating system

*Which operating system are you working on? E.g., Ubuntu Linux, Max OSX, Windows 10, etc.*
macOS 11.5.2
## Description of the problem
synapser does not appear to be available for the M1 Mac. Are there known issues with running synapser on M1 Macs? if not, can the Linux instructions for compiling from scratch be used?

**Comment by thomasyu888** [comment]
Thanks for opening this ticket.  Closing because of the new synapser deployment should work for new M1 macs.  Apologies for the delay @bunnell !
