### ISSUE TITLE
Streaming upload and Google storage.

### ISSUE THREAD

**Issue by emattei** [Sage-Bionetworks/synapser#320]
Hi,
Is it possible to upload a file to Synapse by streaming it? Or do I need to have it on my local machine.
I need to upload files stored in GCP and I would like to avoid having to localize them.

Thank you,
E.

**Comment by thomasyu888** [comment]
Hi @emattei 

There currently isn't a way to upload a file to Synapse by streaming it, so you'd have to download the files locally.  However, there is another option: https://help.synapse.org/docs/Custom-Storage-Locations.2048327803.html#CustomStorageLocations-SettingupanExternalGoogleCloudStorageBucket.

Synapse can support connections to external buckets, but it definitely increases the complexity.  Please let me know if you have any questions.
