### ISSUE TITLE
Unable to Install Synapser

### ISSUE THREAD

**Issue by JManickam13** [Sage-Bionetworks/synapser#321]
## Operating system

I am working on a Mac OSX operating on an M1 chip.

## Description of the problem

I am trying to install synapser into R Studio using the
 `install.packages("synapser", repos=c("http://ran.synapse.org", "http://cran.fhcrc.org"))
`
command and I end up having a large error message detailing dependency conflicts that I am unsure of how to resolve

### Expected behavior

I am not sure exactly how it should look but I do know it is supposed to download correctly.

### Actual behavior

`UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pandas[version='<1.5'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*|>=3.7.1,<3.8.0a0']
  - pysftp -> python[version='2.7.*|3.5.*|3.6.*|3.4.*']
  - pysftp -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.11

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package cryptography conflicts for:
requests[version='<3'] -> urllib3[version='>=1.21.1,<1.26,!=1.25.0,!=1.25.1'] -> cryptography[version='>=1.3.4']
pysftp -> paramiko[version='>=1.17.0'] -> cryptography[version='>=1.1|>=1.5|>=2.5']

Package tzdata conflicts for:
requests[version='<3'] -> python[version='>=3.10,<3.11.0a0'] -> tzdata
jinja2 -> python[version='>=3.11,<3.12.0a0'] -> tzdata
pandas[version='<1.5'] -> pypy3.9[version='>=7.3.9'] -> tzdata
markupsafe -> python[version='>=3.11,<3.12.0a0'] -> tzdata
python=3.11 -> tzdata

Package libsqlite conflicts for:
python=3.11 -> libsqlite[version='>=3.39.4,<4.0a0|>=3.40.0,<4.0a0|>=3.42.0,<4.0a0']
python=3.11 -> sqlite[version='>=3.41.2,<4.0a0'] -> libsqlite[version='3.41.2|3.42.0',build='h58db7d2_1|h58db7d2_0']

Package setuptools conflicts for:
pandas[version='<1.5'] -> numexpr[version='>=2.7.1'] -> setuptools
python=3.11 -> pip -> setuptools
jinja2 -> setuptools
pandas[version='<1.5'] -> setuptools[version='<60.0.0']

Package python_abi conflicts for:
requests[version='<3'] -> python_abi[version='2.7.*|3.6.*|3.6|3.8.*|3.7.*',build='*_cp27m|*_cp37m|*_pypy36_pp73|*_cp38|*_cp36m']
requests[version='<3'] -> certifi[version='>=2017.4.17'] -> python_abi[version='3.10.*|3.9|3.8|3.9.*|3.7',build='*_pypy37_pp73|*_cp39|*_pypy39_pp73|*_cp310|*_pypy38_pp73']
pandas[version='<1.5'] -> numpy[version='>=1.19.5,<2.0a0'] -> python_abi=3.11[build=*_cp311]
markupsafe -> python_abi[version='2.7.*|3.10.*|3.11.*|3.8|3.9.*|3.9|3.8.*|3.7.*|3.7|3.6|3.6.*',build='*_cp27m|*_pypy37_pp73|*_cp310|*_pypy39_pp73|*_cp311|*_pypy38_pp73|*_cp39|*_cp38|*_cp37m|*_pypy36_pp73|*_cp36m']
pysftp -> python=3.6 -> python_abi==3.6[build=*_pypy36_pp73]
pandas[version='<1.5'] -> python_abi[version='3.10.*|3.8.*|3.8|3.9|3.9.*|3.7|3.7.*|3.6|3.6.*',build='*_pypy37_pp73|*_cp310|*_pypy39_pp73|*_pypy38_pp73|*_cp39|*_cp38|*_cp37m|*_pypy36_pp73|*_cp36m']
jinja2 -> markupsafe[version='>=0.23,<2'] -> python_abi[version='2.7.*|3.10.*|3.7.*|3.7|3.9.*|3.8.*|3.6|3.6.*|3.8|3.9|3.11.*',build='*_cp311|*_pypy39_pp73|*_cp27m|*_pypy37_pp73|*_cp310|*_cp37m|*_cp39|*_cp38|*_pypy36_pp73|*_cp36m|*_pypy38_pp73']

Package expat conflicts for:
markupsafe -> pypy3.8[version='>=7.3.11'] -> expat[version='>=2.2.10,<3.0.0a0|>=2.4.1,<3.0a0|>=2.4.7,<3.0a0|>=2.4.8,<3.0a0|>=2.4.9,<3.0a0|>=2.5.0,<3.0a0|>=2.2.9,<3.0.0a0|>=2.3.0,<3.0a0']
pandas[version='<1.5'] -> pypy3.9[version='>=7.3.9'] -> expat[version='>=2.2.10,<3.0.0a0|>=2.3.0,<3.0a0|>=2.4.1,<3.0a0|>=2.4.8,<3.0a0|>=2.4.9,<3.0a0|>=2.5.0,<3.0a0|>=2.2.9,<3.0.0a0']

Package pypy3.9 conflicts for:
markupsafe -> pypy3.9[version='>=7.3.11|>=7.3.9|>=7.3.8']
markupsafe -> python[version='>=3.9,<3.10.0a0'] -> pypy3.9[version='7.3.*|7.3.11.*|7.3.9.*|7.3.8.*']

Package pypy3.7 conflicts for:
markupsafe -> pypy3.7[version='>=7.3.3|>=7.3.4|>=7.3.7']
markupsafe -> python[version='>=3.7,<3.8.0a0'] -> pypy3.7[version='7.3.*|7.3.3.*|7.3.4.*|7.3.5.*|7.3.7.*']

Package pypy3.8 conflicts for:
markupsafe -> python[version='>=3.8,<3.9.0a0'] -> pypy3.8[version='7.3.*|7.3.11.*|7.3.9.*|7.3.8.*']
markupsafe -> pypy3.8[version='>=7.3.11|>=7.3.9|>=7.3.8']
pandas[version='<1.5'] -> pypy3.8[version='>=7.3.9']
pandas[version='<1.5'] -> numpy[version='>=1.19.5,<2.0a0'] -> pypy3.8[version='7.3.*|7.3.11.*|>=7.3.11|>=7.3.8|7.3.9.*|7.3.8.*']
requests[version='<3'] -> certifi[version='>=2017.4.17'] -> pypy3.8[version='7.3.11.*|>=7.3.8|>=7.3.9|7.3.9.*|7.3.8.*']
jinja2 -> setuptools -> pypy3.8[version='7.3.11.*|>=7.3.11|>=7.3.8|>=7.3.9|7.3.9.*|7.3.8.*']

Package certifi conflicts for:
requests[version='<3'] -> certifi[version='>=2017.4.17']
pandas[version='<1.5'] -> setuptools[version='<60.0.0'] -> certifi[version='>=2016.09|>=2016.9.26']
jinja2 -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
requests[version='<3'] -> urllib3[version='>=1.21.1,<1.26,!=1.25.0,!=1.25.1'] -> certifi

Error: one or more Python packages failed to install [error code 1]
Execution halted
ERROR: configuration failed for package ‘synapser’
* removing ‘/Users/manicj/Library/R/arm64/4.2/library/synapser’
Warning in install.packages :
  installation of package ‘synapser’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/6_/0r963bdd7r76s46qwrn44hc4s8314r/T/RtmpdvXKJU/downloaded_`

## Output of `sessionInfo()`

R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cmapR_1.10.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.11                 compiler_4.2.2              pillar_1.9.0               
 [4] cytolib_2.10.1              GenomeInfoDb_1.34.9         XVector_0.38.0             
 [7] MatrixGenerics_1.10.0       bitops_1.0-7                tools_4.2.2                
[10] zlibbioc_1.44.0             lifecycle_1.0.3             tibble_3.2.1               
[13] lattice_0.20-45             pkgconfig_2.0.3             rlang_1.1.1                
[16] Matrix_1.5-1                DelayedArray_0.24.0         cli_3.6.1                  
[19] rstudioapi_0.15.0           GenomeInfoDbData_1.2.9      dplyr_1.1.2                
[22] generics_0.1.3              S4Vectors_0.36.2            vctrs_0.6.3                
[25] IRanges_2.32.0              stats4_4.2.2                grid_4.2.2                 
[28] tidyselect_1.2.0            glue_1.6.2                  Biobase_2.58.0             
[31] R6_2.5.1                    fansi_1.0.4                 RProtoBufLib_2.10.0        
[34] magrittr_2.0.3              matrixStats_1.0.0           BiocGenerics_0.44.0        
[37] GenomicRanges_1.50.2        SummarizedExperiment_1.28.0 flowCore_2.10.0            
[40] utf8_1.2.3                  RCurl_1.98-1.12             rjson_0.2.21

**Comment by JManickam13** [comment]
*apologies if there is not enough information. This is my first time posting a problem

**Comment by thomasyu888** [comment]
Thanks for reporting this issue @JManickam13 .

At first glance, it appears that your system uses python 3.11 which is incompatible with the pandas version that this package requires.

I am working on a client release soon which should hopefully resolve this issue.  Let me dig into your error message more in case I am incorrect.

**Comment by JManickam13** [comment]
In this case, should I download an older version of python? would that make the installation work?

**Comment by thomasyu888** [comment]
Yes, that should work. Sorry for the trouble!
