### ISSUE TITLE
could not find function "synLogin"

### ISSUE THREAD

**Issue by haobeny** [Sage-Bionetworks/synapser#323]
## Operating system

*Windows 10, etc.*

## Description of the problem

*after typing :synLogin(email , password ）,it shows error:could not find function "synLogin" *

R4.2.1.
Thanks.

**Comment by thomasyu888** [comment]
Hi @haobeny ,

Can you try:


```
library(synapser)
synLogin()
```

**Comment by haobeny** [comment]
Thanks for your help. Another problem occured when combine the above two lines:
Error: package or namespace load failed for ‘synapser’:
 loadNamespace()里算'synapser'时.onLoad失败了，详细内容：
  调用: py_run_string_impl(code, local, convert)
  错误: AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Run `reticulate::py_last_error()` for details.
In addition: Warning message:
程辑包‘synapser’是用R版本4.2.3 来建造的.
 
then I followed the solution derived from https://github.com/Sage-Bionetworks/synapseDocs/issues/785, but it still the same.
As a new comer of synapser, I am a little confused. Could you help me with more details. Reall appreciate.

**Comment by thomasyu888** [comment]
Hi @haobeny ,

Apologies for the delays in response.   Could you try to follow these instructions to see if they work: https://docs.google.com/document/d/1-JbgCQxJFNVS7Brs8cFoJwE6o9wtRY2EvRVIzwg5bwA/edit.
