### ISSUE TITLE
PATH and RETICULATE_PATH are ignored when setting up Python virtual environment

### ISSUE THREAD

**Issue by pvo93** [Sage-Bionetworks/synapser#327]
## Operating system

Linux RHEL8 in a shared research high performance computing environment (Mayo Clinic) where I don't have root privileges.

## Description of the problem

When I try to install synapser, it always uses /usr/bin/python2.7 even though that's not the python in my PATH or RETICULATE_PATH. This leads to multiple warnings that 2.7 is deprecated. Then the installation fails because it can't find a recent enough version of pandas. Even after I hack the code to get around that, it can't install the python client version 3.0.0 as specified in your installPythonClient.R file.

### Expected behavior

I expect it to use the python specified in PATH or RETICULATE_PATH

### Actual behavior

[wa02042@mforgehn4 synapser]$ R --vanilla

R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> .libPaths("/usr/local/biotools/rpackages/R-4.2.2-2023-02-01")
> system("which python")
/usr/local/biotools/python/3.10.7/bin/python
> system("\\rm -rf ~/.virtualenvs/r-reticulate")
> install.packages("synapser", repos = c("http://ran.synapse.org", "http://cran.fhcrc.org"))
Installing package into ‘/usr/local/biotools/rpackages/R-4.2.2-2023-02-01’
(as ‘lib’ is unspecified)
trying URL 'http://ran.synapse.org/src/contrib/synapser_1.2.0.143.tar.gz'
Content type 'application/x-tar' length 156600 bytes (152 KB)
==================================================
downloaded 152 KB

* installing *source* package ‘synapser’ ...
** using staged installation
[1] "*** Using Python Configuration:"
**Using Python: /usr/bin/python2.7**
Creating virtual environment 'r-reticulate' ... 
+ /usr/bin/python2.7 -m virtualenv -p '/usr/bin/python2.7' /home/mayo/wa02042/.virtualenvs/r-reticulate
created virtual environment CPython2.7.18.final.0-64 in 5297ms
  creator CPython2Posix(dest=/home/mayo/wa02042/.virtualenvs/r-reticulate, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/home/mayo/wa02042/.local/share/virtualenv)
    added seed packages: pip==20.3.4, setuptools==44.1.1, wheel==0.37.1
  activators NushellActivator,PythonActivator,FishActivator,CShellActivator,PowerShellActivator,BashActivator
Done!
Installing packages: pip, wheel, setuptools
+ /home/mayo/wa02042/.virtualenvs/r-reticulate/bin/python -m pip install --upgrade pip wheel setuptools
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already up-to-date: pip in /home/mayo/wa02042/.virtualenvs/r-reticulate/lib/python2.7/site-packages (20.3.4)
Requirement already up-to-date: wheel in /home/mayo/wa02042/.virtualenvs/r-reticulate/lib/python2.7/site-packages (0.37.1)
Requirement already up-to-date: setuptools in /home/mayo/wa02042/.virtualenvs/r-reticulate/lib/python2.7/site-packages (44.1.1)
Installing packages: numpy
+ /home/mayo/wa02042/.virtualenvs/r-reticulate/bin/python -m pip install --upgrade --no-user numpy
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting numpy
  Using cached numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl (17.0 MB)
Installing collected packages: numpy
Successfully installed numpy-1.16.6
Virtual environment 'r-reticulate' successfully created.
Using virtual environment '/home/mayo/wa02042/.virtualenvs/r-reticulate' ...
+ /home/mayo/wa02042/.virtualenvs/r-reticulate/bin/python -m pip install --upgrade --no-user 'requests<3' 'pandas~=2.0.0' pysftp jinja2 markupsafe
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting requests<3
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
ERROR: Could not find a version that satisfies the requirement pandas~=2.0.0 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2)
ERROR: No matching distribution found for pandas~=2.0.0
Error: Error installing package(s): "'requests<3'", "'pandas~=2.0.0'", "pysftp", "jinja2", "markupsafe"
Execution halted
ERROR: configuration failed for package ‘synapser’
* removing ‘/usr/local/biotools/rpackages/R-4.2.2-2023-02-01/synapser’
* restoring previous ‘/usr/local/biotools/rpackages/R-4.2.2-2023-02-01/synapser’

The downloaded source packages are in
	‘/tmp/RtmpE09Aui/downloaded_packages’
Warning message:
In install.packages("synapser", repos = c("http://ran.synapse.org",  :
  installation of package ‘synapser’ had non-zero exit status
> 

## Output of `sessionInfo()`

> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux 8.8 (Ootpa)

Matrix products: default
BLAS:   /usr/lib64/libblas.so.3.8.0
LAPACK: /usr/lib64/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=C              
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.2 tools_4.2.2   
>

**Comment by thomasyu888** [comment]
HI @pvo93 ,

Thanks for using synapser.  Can you try doing this:

```
require(reticulate)
reticulate::use_python("/usr/local/biotools/python/3.10.7/bin/python")
install.packages("synapser", repos = c("http://ran.synapse.org/", "http://cran.fhcrc.org/"))
```

**Comment by pvo93** [comment]
It still seems to be looking for Python 2.7 libraries.

> require(reticulate)
Loading required package: reticulate
> install.packages("synapser", repos = c("http://ran.synapse.org/", "http://cran.fhcrc.org/"))
Installing package into ‘/usr/local/biotools/rpackages/R-4.2.2-2023-02-01’
(as ‘lib’ is unspecified)
trying URL 'http://ran.synapse.org/src/contrib/synapser_1.2.0.143.tar.gz'
Content type 'application/x-tar' length 156600 bytes (152 KB)
==================================================
downloaded 152 KB

* installing *source* package ‘synapser’ ...
** using staged installation
Error: PyType_GetFlags - /usr/lib64/libpython2.7.so.1.0: undefined symbol: PyType_GetFlags
In addition: Warning message:
In py_initialize(config$python, config$libpython, config$pythonhome,  :
  Python 2 reached EOL on January 1, 2020. Python 2 compatability will be removed in an upcoming reticulate release.
Execution halted
[1] "*** Using Python Configuration:"
virtualenv: r-reticulate
Using virtual environment '/home/mayo/wa02042/.virtualenvs/r-reticulate' ...
+ /home/mayo/wa02042/.virtualenvs/r-reticulate/bin/python -m pip install --upgrade --no-user 'requests<3' 'pandas~=2.0.0' pysftp jinja2 markupsafe
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting requests<3
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
ERROR: Could not find a version that satisfies the requirement pandas~=2.0.0 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2)
ERROR: No matching distribution found for pandas~=2.0.0
Error: Error installing package(s): "'requests<3'", "'pandas~=2.0.0'", "pysftp", "jinja2", "markupsafe"
Execution halted
ERROR: configuration failed for package ‘synapser’
* removing ‘/usr/local/biotools/rpackages/R-4.2.2-2023-02-01/synapser’
* restoring previous ‘/usr/local/biotools/rpackages/R-4.2.2-2023-02-01/synapser’

The downloaded source packages are in
	‘/tmp/RtmpE09Aui/downloaded_packages’
Warning message:
In install.packages("synapser", repos = c("http://ran.synapse.org/",  :
  installation of package ‘synapser’ had non-zero exit status
>

**Comment by thomasyu888** [comment]
HI @pvo93 

Did you run this command before installing?
```
reticulate::use_python("/usr/local/biotools/python/3.10.7/bin/python")
```

**Comment by pvo93** [comment]
Yes, I did. I ran it a second time after deleting ~/.virtualenvs/r-reticulate and forgot to include that line to paste in the output, but I had run it earlier in the session. My apologies. I just ran it again in a new session.

> require(reticulate)
Loading required package: reticulate
> reticulate::use_python("/usr/local/biotools/python/3.10.7/bin/python")
> install.packages("synapser", repos = c("http://ran.synapse.org/", "http://cran.fhcrc.org/"))
Installing package into ‘/usr/local/biotools/rpackages/R-4.2.2-2023-02-01’
(as ‘lib’ is unspecified)
trying URL 'http://ran.synapse.org/src/contrib/synapser_1.2.0.143.tar.gz'
Content type 'application/x-tar' length 156600 bytes (152 KB)
==================================================
downloaded 152 KB

* installing *source* package ‘synapser’ ...
** using staged installation
Error: PyType_GetFlags - /usr/lib64/libpython2.7.so.1.0: undefined symbol: PyType_GetFlags
In addition: Warning message:
In py_initialize(config$python, config$libpython, config$pythonhome,  :
  Python 2 reached EOL on January 1, 2020. Python 2 compatability will be removed in an upcoming reticulate release.
Execution halted
[1] "*** Using Python Configuration:"
virtualenv: r-reticulate
Using virtual environment '/home/mayo/wa02042/.virtualenvs/r-reticulate' ...
+ /home/mayo/wa02042/.virtualenvs/r-reticulate/bin/python -m pip install --upgrade --no-user 'requests<3' 'pandas~=2.0.0' pysftp jinja2 markupsafe
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting requests<3
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
ERROR: Could not find a version that satisfies the requirement pandas~=2.0.0 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2)
ERROR: No matching distribution found for pandas~=2.0.0
Error: Error installing package(s): "'requests<3'", "'pandas~=2.0.0'", "pysftp", "jinja2", "markupsafe"
Execution halted
ERROR: configuration failed for package ‘synapser’
* removing ‘/usr/local/biotools/rpackages/R-4.2.2-2023-02-01/synapser’
* restoring previous ‘/usr/local/biotools/rpackages/R-4.2.2-2023-02-01/synapser’

The downloaded source packages are in
	‘/tmp/RtmpJvldw0/downloaded_packages’
Warning message:
In install.packages("synapser", repos = c("http://ran.synapse.org/",  :
  installation of package ‘synapser’ had non-zero exit status

**Comment by thomasyu888** [comment]
Hi @pvo93 ,

Apologies for the delays in response - I have found the bug and am attempting to fix it for the upcoming release.  In the meantime, a not as ideal way to interact with the client in R can be found here: https://github.com/Sage-Bionetworks/synapsePythonClient/blob/develop/docs/articles/reticulate.rst.

You would use reticulate directly to install the client:

```
require(reticulate)
reticulate::use_python("/usr/local/biotools/python/3.10.7/bin/python")
reticulate::py_install("synapseclient")
```

The rest of the instructions can be found in the link above.  Please let me know if that doesn't work while I attempt to fix the issue.

**Comment by thomasyu888** [comment]
The new versions of the client should have this fixed!  closing for now
