### ISSUE TITLE
Login in problem with error "Error value[[3L]](cond):    You are not logged in and do not have access to a requested resource."

### ISSUE THREAD

**Issue by Bamrock** [Sage-Bionetworks/synapser#333]
Hi, when I try to log in using R, synLogin(authToken = "myToken"), I got an error “Error value[3L]: You are not logged in and do not have access to a requested resource. “, can you help me to figure out the problem? Thanks

**Comment by thomasyu888** [comment]
HI @Bamrock 

Sorry for the trouble.  Could you provide your sessionInfo()?  You’ve most likely seen this page, but I will provide a link: [Manage Synapse Credentials](https://r-docs.synapse.org/articles/manageSynapseCredentials.html) 

```
library(synapser)
synLogin(authToken="<mytoken here>")
# Welcome, Thomas Yu!

entity = synGet("syn21683345")
# Downloading  [####################]100.00%   303.4kB/303.4kB (1.5MB/s) data_guide (24).pdf Done...
entity$name
# [1] "current_data_guide.pdf"
```

**Comment by Bamrock** [comment]
Hi, Thomas Yun
Below is my sessionInfo()
> library(synapser) TERMS OF USE NOTICE: When using Synapse, remember that the terms and conditions of use require that you: 1) Attribute data contributors when discussing these data or results from these data. 2) Not discriminate, identify, or recontact individuals or groups represented by the data. 3) Use and contribute only data de-identified to HIPAA standards. 4) Redistribute data only under these same terms of use. > synLogin(authToken="ukb-ppp-hu") 错误于value[[3L]](cond): You are not logged in and do not have access to a requested resource. 
> 
------------------------------------------------------------------
发件人：Thomas Yu ***@***.***>
发送时间：2024年6月2日(星期日) 13:51
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [Sage-Bionetworks/synapser] Login in problem with error "Error value[[3L]](cond): You are not logged in and do not have access to a requested resource." (Issue #333)
HI @Bamrock <https://github.com/Bamrock >
Sorry for the trouble. Could you provide your sessionInfo()? You’ve most likely seen this page, but I will provide a link: Manage Synapse Credentials <https://r-docs.synapse.org/articles/manageSynapseCredentials.html >
library(synapser) synLogin(authToken="<mytoken here>") # Welcome, Thomas Yu! entity = synGet("syn21683345") # Downloading [####################]100.00% 303.4kB/303.4kB (1.5MB/s) data_guide (24).pdf Done... entity$name # [1] "current_data_guide.pdf"

**Comment by thomasyu888** [comment]
HI @Bamrock ,

Can you follow instructions here: https://help.synapse.org/docs/Managing-Your-Account.2055405596.html#ManagingYourAccount-PersonalAccessTokens to create a personal access token?

"ukb-ppp-hu" is not a valid access token.

**Comment by Bamrock** [comment]
Sorry, my sessionInfo() is below:
> sessionInfo() R version 4.4.0 (2024-04-24 ucrt) Platform: x86_64-w64-mingw32/x64 Running under: Windows 10 x64 (build 17763) Matrix products: default locale: [1] LC_COLLATE=Chinese (Simplified)_China.936 [2] LC_CTYPE=Chinese (Simplified)_China.936 [3] LC_MONETARY=Chinese (Simplified)_China.936 [4] LC_NUMERIC=C [5] LC_TIME=Chinese (Simplified)_China.936 time zone: Asia/Shanghai tzcode source: internal attached base packages: [1] stats graphics grDevices utils datasets methods base loaded via a namespace (and not attached): [1] compiler_4.4.0 tools_4.4.0 
> 
------------------------------------------------------------------
发件人：Thomas Yu ***@***.***>
发送时间：2024年6月2日(星期日) 13:51
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [Sage-Bionetworks/synapser] Login in problem with error "Error value[[3L]](cond): You are not logged in and do not have access to a requested resource." (Issue #333)
HI @Bamrock <https://github.com/Bamrock >
Sorry for the trouble. Could you provide your sessionInfo()? You’ve most likely seen this page, but I will provide a link: Manage Synapse Credentials <https://r-docs.synapse.org/articles/manageSynapseCredentials.html >
library(synapser) synLogin(authToken="<mytoken here>") # Welcome, Thomas Yu! entity = synGet("syn21683345") # Downloading [####################]100.00% 303.4kB/303.4kB (1.5MB/s) data_guide (24).pdf Done... entity$name # [1] "current_data_guide.pdf"

**Comment by Bamrock** [comment]
Hi, Thomas Yu
I have follow the instructions, and create a new token (synapse_login_bamrock), when I login with this new token, I still get the same error.
Is there a requirement for a token? I didn't see the requirement on the token, so I create it contaning letters and "_".
Below is the email I got after I create the token.
------------------------------------------------------------------
发件人：Thomas Yu ***@***.***>
发送时间：2024年6月2日(星期日) 15:07
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [Sage-Bionetworks/synapser] Login in problem with error "Error value[[3L]](cond): You are not logged in and do not have access to a requested resource." (Issue #333)
HI @Bamrock <https://github.com/Bamrock > ,
Can you follow instructions here: https://help.synapse.org/docs/Managing-Your-Account.2055405596.html#ManagingYourAccount-PersonalAccessTokens <https://help.synapse.org/docs/Managing-Your-Account.2055405596.html#ManagingYourAccount-PersonalAccessTokens > to create a personal access token?
"ukb-ppp-hu" is not a valid access token.

**Comment by thomasyu888** [comment]
HI @Bamrock 

When you create a token, you should be taken to a page like this:

<img width="576" alt="image" src="https://github.com/Sage-Bionetworks/synapser/assets/10556275/52015dd0-c7b7-4347-a11a-0f894d907435">

Your token isn't going to be what you named the token but it'll be:

```
eyJ0eXAiOiJKV1QiLCJraWQiOiJXN05OOldMSlQ6SjVSSzpMN1RMOlQ3TDc6M1ZYNjpKRU9VOjY0NFI6VTNJWDo1S1oyOjdaQ0s6RlBUSCIsImFsZyI6IsdfsdfMjU2In0.eyJhY2Nlc3MiOnsic2NvcGUiOlsidmlldyIsImRvd25sb2FkIiwibW9kaWZ5Il0sIm9pZGNfY2xhaW1zIjp7fX0sInRva2VuX3R5cGUiOiJQRVJTT05BTF9BQ0NFU1NfVE9LRU4iLCJpc3MiOiJodHRwczovL3JlcG8tcHJvZC5wcm9kLnNhZ2ViYXNlLm9yZasdfasdfasdfasdf.......
```

so when you login:

```
library(synapser)
synLogin(authToken="eyJ0eXAiOiJKV1QiLCJraWQiOiJXN05OOldMSlQ6SjVSSzpMN1RMOlQ3TDc6M1ZYNjpKRU9VOjY0NFI6VTNJWDo1S1oyOjdaQ0s6RlBUSCIsImFsZyI6IsdfsdfMjU2In0.eyJhY2Nlc3MiOnsic2NvcGUiOlsidmlldyIsImRvd25sb2FkIiwibW9kaWZ5Il0sIm9pZGNfY2xhaW1zIjp7fX0sInRva2VuX3R5cGUiOiJQRVJTT05BTF9BQ0NFU1NfVE9LRU4iLCJpc3MiOiJodHRwczovL3JlcG8tcHJvZC5wcm9kLnNhZ2ViYXNlLm9yZasdfasdfasdfasdf.")
```

**Comment by Bamrock** [comment]
Hi, Thomas Yu
I did it as you said, but still got the same error. Below is the detail information.
> library(synapser) TERMS OF USE NOTICE: When using Synapse, remember that the terms and conditions of use require that you: 1) Attribute data contributors when discussing these data or results from these data. 2) Not discriminate, identify, or recontact individuals or groups represented by the data. 3) Use and contribute only data de-identified to HIPAA standards. 4) Redistribute data only under these same terms of use. > synLogin(authToken="eyJ0eXAiOiJKV1QiLCJraWQiOiJXN05OOldMSlQ6SjVSSzpMN1RMOlQ3TDc6M1ZYNjpKRU9VOjY0NFI6VTNJWDo1S1oyOjdaQ0s6RlBUSCIsImFsZyI6IlJTMjU2In0.eyJhY2Nlc3MiOnsic2NvcGUiOlsidmlldyIsImRvd25sb2FkIiwibW9kaWZ5Il0sIm9pZGNfY2xhaW1zIjp7fX0sInRva2VuX3R5cGUiOiJQRVJTT05BTF9BQ0NFU1NfVE9LRU4iLCJpc3MiOiJodHRwczovL3JlcG8tcHJvZC5wcm9kLnNhZ2ViYXNlLm9yZy9hdXRoL3YxIiwiYXVkIjoiMCIsIm5iZiI6MTcxNzMxMzg0MywiaWF0IjoxNzE3MzEzODQzLCJqdGkiOiI4NjIzIiwic3ViIjoiMzUwNDQwOSJ9.UDUHZgdHbLAXaXmTLG8U-1krlyTsZeXi6smMrw-iJPyPsCG2IKIwTc0xszfjoQEcHk4UVqZKuuzbuMjTPAzX_-FdXoXDZbPTG3D0mM5h-25-YyAhXFT_uTSHDw2PcDDLwSFK0CGcrC1WDwvFLvz1KqHlLa1a1k1IqEwHJ5rq0uPT91qxiAAgT-3-68MpPggTvcoT74ngzOFwL9qEGXUd6-24ECxask3qqcqqMrnV0piAoLSCraQPItUZrXJowkdDgWBWl1Fd49EXxpBDUmy4OA8AyQajM4wEu2nsKDRuVf51DBsi82x9jK2JRfKuicLlVWZjOdqQuhnHu2Si-LJs_A") 错误于value[[3L]](cond): You are not logged in and do not have access to a requested resource. >
------------------------------------------------------------------
发件人：Thomas Yu ***@***.***>
发送时间：2024年6月2日(星期日) 15:34
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [Sage-Bionetworks/synapser] Login in problem with error "Error value[[3L]](cond): You are not logged in and do not have access to a requested resource." (Issue #333)
HI @Bamrock <https://github.com/Bamrock >
When you create a token, you should be taken to a page like this:
image.png (view on web) <https://github.com/Sage-Bionetworks/synapser/assets/10556275/52015dd0-c7b7-4347-a11a-0f894d907435 >
Your token isn't going to be what you named the token but it'll be:
eyJ0eXAiOiJKV1QiLCJraWQiOiJXN05OOldMSlQ6SjVSSzpMN1RMOlQ3TDc6M1ZYNjpKRU9VOjY0NFI6VTNJWDo1S1oyOjdaQ0s6RlBUSCIsImFsZyI6IsdfsdfMjU2In0.eyJhY2Nlc3MiOnsic2NvcGUiOlsidmlldyIsImRvd25sb2FkIiwibW9kaWZ5Il0sIm9pZGNfY2xhaW1zIjp7fX0sInRva2VuX3R5cGUiOiJQRVJTT05BTF9BQ0NFU1NfVE9LRU4iLCJpc3MiOiJodHRwczovL3JlcG8tcHJvZC5wcm9kLnNhZ2ViYXNlLm9yZasdfasdfasdfasdf....... 
so when you login:
library(synapser) synLogin(authToken="eyJ0eXAiOiJKV1QiLCJraWQiOiJXN05OOldMSlQ6SjVSSzpMN1RMOlQ3TDc6M1ZYNjpKRU9VOjY0NFI6VTNJWDo1S1oyOjdaQ0s6RlBUSCIsImFsZyI6IsdfsdfMjU2In0.eyJhY2Nlc3MiOnsic2NvcGUiOlsidmlldyIsImRvd25sb2FkIiwibW9kaWZ5Il0sIm9pZGNfY2xhaW1zIjp7fX0sInRva2VuX3R5cGUiOiJQRVJTT05BTF9BQ0NFU1NfVE9LRU4iLCJpc3MiOiJodHRwczovL3JlcG8tcHJvZC5wcm9kLnNhZ2ViYXNlLm9yZasdfasdfasdfasdf.")

**Comment by thomasyu888** [comment]
Hi @Bamrock ,

You just shared your personal access token publicly, please revoke it. That said, I was able to login via the pasted token

```
> library(synapser)

New synapser version detected:
    You are using synapser version 1.0.59.
    synapser version 2.0.0.200 is detected at http://ran.synapse.org.
    To upgrade to the latest version of synapser, please run the following command:
    install.packages("synapser", repos="http://ran.synapse.org")


TERMS OF USE NOTICE:
  When using Synapse, remember that the terms and conditions of use require that you:
  1) Attribute data contributors when discussing these data or results from these data.
  2) Not discriminate, identify, or recontact individuals or groups represented by the data.
  3) Use and contribute only data de-identified to HIPAA standards.
  4) Redistribute data only under these same terms of use.

> synLogin(authToken="eyJ0eXAiOiJKV1QiLCJraWQiOiJXN05OOldMSlQ6SjVSSzpMN1RMOlQ3TDc6M1ZYNjpKRU9VOjY0NFI6VTNJWDo1S1oyOjdaQ0s6RlBUSCIsImFsZyI6IlJTMjU2In0.eyJhY2Nlc3MiOnsic2NvcGUiOlsidmlldyIsImRvd25sb2FkIiwibW9kaWZ5Il0sIm9pZGNfY2xhaW1zIjp7fX0sInR.....")
Welcome, qiuqiu2021!
```

Are you on an institution network?  If so, it might be that some of these IP's are being blocked: https://help.synapse.org/docs/Synapse-Infrastructure.2835382273.html.

**Comment by Bamrock** [comment]
Hi, Thomas Yu
Thanks for remindering me my shared token, I will change my token. 
I try to login with Command Line Client rather than using R, it works and I successfully login. Maybe there are some problems in my R.
Thank you very much for your help. Have a nice weekends. :-)
------------------------------------------------------------------
发件人：Thomas Yu ***@***.***>
发送时间：2024年6月2日(星期日) 16:04
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [Sage-Bionetworks/synapser] Login in problem with error "Error value[[3L]](cond): You are not logged in and do not have access to a requested resource." (Issue #333)
Hi @Bamrock <https://github.com/Bamrock > ,
You just shared your personal access token publicly, please revoke it. That said, I was able to login via the pasted token
> library(synapser) New synapser version detected: You are using synapser version 1.0.59. synapser version 2.0.0.200 is detected at http://ran.synapse.org. To upgrade to the latest version of synapser, please run the following command: install.packages("synapser", repos="http://ran.synapse.org") TERMS OF USE NOTICE: When using Synapse, remember that the terms and conditions of use require that you: 1) Attribute data contributors when discussing these data or results from these data. 2) Not discriminate, identify, or recontact individuals or groups represented by the data. 3) Use and contribute only data de-identified to HIPAA standards. 4) Redistribute data only under these same terms of use. > synLogin(authToken="eyJ0eXAiOiJKV1QiLCJraWQiOiJXN05OOldMSlQ6SjVSSzpMN1RMOlQ3TDc6M1ZYNjpKRU9VOjY0NFI6VTNJWDo1S1oyOjdaQ0s6RlBUSCIsImFsZyI6IlJTMjU2In0.eyJhY2Nlc3MiOnsic2NvcGUiOlsidmlldyIsImRvd25sb2FkIiwibW9kaWZ5Il0sIm9pZGNfY2xhaW1zIjp7fX0sInR.....") Welcome, qiuqiu2021! 
Are you on an institution network? If so, it might be that some of these IP's are being blocked: https://help.synapse.org/docs/Synapse-Infrastructure.2835382273.html <https://help.synapse.org/docs/Synapse-Infrastructure.2835382273.html >.

**Comment by thomasyu888** [comment]
Hi @Bamrock ,

No problem - glad you were able to get it to work via the command line.  Strange that it doesn't work with R...  I'll close this request for now.  Thanks again!
